def add_hyphens(words):
    return ["-".join(word.split()) for word in words]


def split_words(words):
    combined_list = []
    first_list = []
    second_list = []

    for word in words:
        split_words = word.split("-")
        combined_list.append(word)
        first_list.append(split_words[0])
        if len(split_words) > 1:
            second_list.append(split_words[1])
        else:
            second_list.append("")

    return combined_list, first_list, second_list


listy = [
    "Abdominal aortic aneurysm",
    "Acne",
    "Acute cholecystitis",
    "Acute lymphoblastic leukaemia",
    "Acute lymphoblastic leukaemia: Children",
    "Acute lymphoblastic leukaemia: Teenagers and young adults",
    "Acute myeloid leukaemia",
    "Acute myeloid leukaemia: Children",
    "Acute myeloid leukaemia: Teenagers and young adults",
    "Acute pancreatitis",
    "Addison's ",
    "Alcohol-related liver ",
    "Allergic rhinitis",
    "Allergies",
    "Alzheimer's ",
    "Anal cancer",
    "Anaphylaxis",
    "Angioedema",
    "Ankylosing spondylitis",
    "Anorexia nervosa",
    "Anxiety",
    "Anxiety disorders in children",
    "Appendicitis",
    "Arthritis",
    "Asbestosis",
    "Asthma",
    "Atopic eczema",
    "Attention deficit hyperactivity disorder (ADHD)",
    "Autistic spectrum disorder (ASD)",
    "Bacterial vaginosis",
    "Benign prostate enlargement",
    "Bile duct cancer (cholangiocarcinoma)",
    "Binge eating",
    "Bipolar disorder",
    "Bladder cancer",
    "Blood poisoning (sepsis)",
    "Bone cancer",
    "Bone cancer: Teenagers and young adults",
    "Bowel cancer",
    "Bowel incontinence",
    "Bowel polyps",
    "Brain stem death",
    "Brain tumours",
    "Brain tumours: Children",
    "Brain tumours: Teenagers and young adults",
    "Breast cancer (female)",
    "Breast cancer (male)",
    "Bronchiectasis",
    "Bronchitis",
    "Bulimia",
    "Bunion",
    "Carcinoidand-carcinoid tumours",
    "Catarrh",
    "Cellulitis",
    "Cerebral palsy",
    "Cervical cancer",
    "Chest infection",
    "Chest pain",
    "Chickenpox",
    "Chilblains",
    "Chlamydia",
    "Chronic fatigue ",
    "Chronic kidney ",
    "Chronic lymphocytic leukaemia",
    "Chronic myeloid leukaemia",
    "Chronic obstructive pulmonary ",
    "Chronic pain",
    "Chronic pancreatitis",
    "Cirrhosis",
    "Clostridium difficile",
    "Coeliac ",
    "Cold sore",
    "Coma",
    "Common cold",
    "Common heart conditions",
    "Congenital heart ",
    "Conjunctivitis",
    "Constipation",
    "Coronavirus (COVID-19)",
    "Cough",
    "Crohn's ",
    "Croup",
    "Cystic fibrosis",
    "Cystitis",
    "Deafblindness",
    "Deep vein thrombosis",
    "Dehydration",
    "Dementia",
    "Dementia with Lewy bodies",
    "Dental abscess",
    "Depression",
    "Dermatitis herpetiformis",
    "Diabetes",
    "Diarrhoea",
    "Discoid eczema",
    "Diverticularand-diverticulitis",
    "Dizziness (Lightheadedness)",
    "Down's ",
    "Dry mouth",
    "Dysphagia (swallowing problems)",
    "Dystonia",
    "Earache",
    "Earwax build-up",
    "Ebola virus ",
    "Ectopic pregnancy",
    "Edwards' ",
    "Endometriosis",
    "Epilepsy",
    "Erectile dysfunction (impotence)",
    "Escherichia coli (E. coli) O157",
    "Ewing sarcoma",
    "Ewing sarcoma: Children",
    "Eye cancer",
    "Febrile seizures",
    "Feeling of something in your throat (Globus)",
    "Fever in adults",
    "Fever in children",
    "Fibroids",
    "Fibromyalgia",
    "Flatulence",
    "Flu",
    "Foetal alcohol ",
    "Food poisoning",
    "Functional neurological disorder (FND)",
    "Fungal nail infection",
    "Gallbladder cancer",
    "Gallstones",
    "Ganglion cyst",
    "Gastroenteritis",
    "Gastro-oesophageal reflux  (GORD)",
    "Genital herpes",
    "Genital symptoms",
    "Genital warts",
    "Germ cell tumours",
    "Glandular fever",
    "Gonorrhoea",
    "Gout",
    "Gum ",
    "Haemorrhoids (piles)",
    "Hand, foot and mouth ",
    "Hay fever",
    "Head and neck cancer",
    "Head lice and nits",
    "Headaches",
    "Hearing loss",
    "Heart failure",
    "Hepatitis A",
    "Hepatitis B",
    "Hepatitis C",
    "Hiatus hernia",
    "High cholesterol",
    "HIV",
    "Hodgkin lymphoma",
    "Hodgkin lymphoma: Children",
    "Hodgkin lymphoma: Teenagers and young adults",
    "Huntington's ",
    "Hyperglycaemia (high blood sugar)",
    "Hyperhidrosis",
    "Hypoglycaemia (low blood sugar)",
    "Idiopathic pulmonary fibrosis",
    "Impetigo",
    "Indigestion",
    "Ingrown toenail",
    "Inherited heart conditions",
    "Insomnia",
    "Iron deficiency anaemia",
    "Irritable bowel  (IBS)",
    "Irritable hip",
    "Itching",
    "Itchy bottom",
    "Kaposi's sarcoma",
    "Kidney cancer",
    "Kidney infection",
    "Kidney stones",
    "Labyrinthitis",
    "Lactose intolerance",
    "Laryngeal (larynx) cancer",
    "Laryngitis",
    "Leg cramps",
    "Lichen planus",
    "Liver cancer",
    "Liver ",
    "Liver tumours",
    "Loss of libido",
    "Lung cancer",
    "Lupus",
    "Lyme ",
    "Lymphoedema",
    "Lymphogranuloma venereum (LGV)",
    "Malaria",
    "Malignant brain tumour (cancerous)",
    "Malnutrition",
    "Measles",
    "Meningitis",
    "Menopause",
    "Mesothelioma",
    "Middle ear infection (otitis media)",
    "Migraine",
    "Miscarriage",
    "Motor neurone  (MND)",
    "Mouth cancer",
    "Mouth ulcer",
    "Multiple myeloma",
    "Multiple sclerosis (MS)",
    "Mumps",
    "Meniere's ",
    "Myasthenia gravis",
    "Nasal and sinus cancer",
    "Nasopharyngeal cancer",
    "Neuroblastoma: Children",
    "Neuroendocrine tumours",
    "Non-alcoholic fatty liver  (NAFLD)",
    "Non-Hodgkin lymphoma",
    "Non-Hodgkin lymphoma: Children",
    "Norovirus",
    "Nosebleed",
    "Obesity",
    "Obsessive compulsive disorder (OCD)",
    "Obstructive sleep apnoea",
    "Oesophageal cancer",
    "Oral thrush in adults",
    "Osteoporosis",
    "Osteosarcoma",
    "Otitis externa",
    "Ovarian cancer",
    "Ovarian cancer: Teenagers and young adults",
    "Ovarian cyst",
    "Overactive thyroid",
    "Paget'sof-the nipple",
    "Pancreatic cancer",
    "Panic disorder",
    "Parkinson's ",
    "Patau's ",
    "Pelvic inflammatory ",
    "Pelvic organ prolapse",
    "Penile cancer",
    "Peripheral neuropathy",
    "Personality disorder",
    "Pleurisy",
    "Pneumonia",
    "Polymyalgia rheumatica",
    "Post-polio ",
    "Post-traumatic stress disorder (PTSD)",
    "Postnatal depression",
    "Pregnancy and baby",
    "Pressure ulcers",
    "Prostate cancer",
    "Psoriasis",
    "Psoriatic arthritis",
    "Psychosis",
    "Pubic lice",
    "Rare tumours",
    "Raynaud's phenomenon",
    "Reactive arthritis",
    "Restless legs ",
    "Retinoblastoma: Children",
    "Rhabdomyosarcoma",
    "Rheumatoid arthritis",
    "Ringworm and other fungal infections",
    "Rosacea",
    "Scabies",
    "Scarlet fever",
    "Schizophrenia",
    "Scoliosis",
    "Septic shock",
    "Shingles",
    "Shortness of breath",
    "Sickle cell ",
    "Sinusitis",
    "Sjogren's ",
    "Skin cancer (melanoma)",
    "Skin cancer (non-melanoma)",
    "Slapped cheek ",
    "Soft tissue sarcomas",
    "Soft tissue sarcomas: Teenagers and young adults",
    "Sore throat",
    "Spleen problems and spleen removal",
    "Stillbirth",
    "Stomach ache and abdominal pain",
    "Stomach cancer",
    "Stomach ulcer",
    "Streptococcus A (strep A)",
    "Stress, anxiety and low mood",
    "Stroke",
    "Sudden infant death  (SIDS)",
    "Suicide",
    "Sunburn",
    "Swollen glands",
    "Syphilis",
    "Testicular cancer",
    "Testicular cancer: Teenagers and young adults",
    "Testicular lumps and swellings",
    "Thirst",
    "Threadworms",
    "Thrush",
    "Thyroid cancer",
    "Thyroid cancer: Teenagers and young adults",
    "Tinnitus",
    "Tonsillitis",
    "Tooth decay",
    "Toothache",
    "Transient ischaemic attack (TIA)",
    "Trigeminal neuralgia",
    "Tuberculosis (TB)",
    "Type 1 diabetes",
    "Type 2 diabetes",
    "Trichomonas infection",
    "Transverse myelitis",
    "Ulcerative colitis",
    "Underactive thyroid",
    "Urinary incontinence",
    "Urinary tract infection (UTI)",
    "Urinary tract infection (UTI) in children",
    "Urticaria (hives)",
    "Vaginal cancer",
    "Vaginal discharge",
    "Varicose eczema",
    "Venous leg ulcer",
    "Vertigo",
    "Vitamin B12 or folate deficiency anaemia",
    "Vomiting in adults",
    "Vulval cancer",
    "Warts and verrucas",
    "Whooping cough",
    "Wilms' tumour",
    "Womb (uterus) cancer",
    "Yellow fever",
    "Leaky Gut ",
    "Non-Celiac Gluten Sensitivity",
    "Hepatitis",
    "Gilbert's ",
    "Slow Transit Constipation",
    "Tourette's ",
    "Tic Disorder",
    "Essential Tremor",
    "Pulmonary Neuroendocrine Cell Hyperplasia",
    "Diffuse Idiopathic Pulmonary Neuroendocrine Cell Hyperplasia (DIPNECH)",
    "Asthmatic Bronchitis",
    "Bronchiectasis",
    "Eosinophilic Gastrointestinal Disorder",
    "Anosmia",
    "Parosmia",
    "Breast Cancer",
    "Overactive Bladder",
    "Celiac ",
    "Small Intestine Bacterial Overgrowth (SIBO)",
    "Lactose Intolerance",
    "Lewy Body Dementia",
    "Transient Global Amnesia",
    "Temporal Lobe Epilepsy",
    "Traumatic Brain Injury",
    "Subarachnoid Hemorrhage",
    'Colorectal Cancer (presumably from "COOLLORLASTOMA")',
    "Susac's ",
    "Non-Epileptic Seizures (PNES or NEAD)",
    "Gastroparesis",
    "Deep Vein Thrombosis",
    "Varicose Veins",
    "Chronic Venous Insufficiency",
    "Lymphedema",
    "Turner's ",
    "Lipodema",
    "Schizoaffective Disorder",
    "Rapid Cycling Bipolar Disorder",
    "Borderline Personality Disorder",
    "Lichen Planus",
    "Candidiasis",
    "Recurrent Bacterial Vaginosis",
    "Human Papillomavirus (HPV)",
    "Tinnitus",
    "Temporomandibular Joint Disorders",
    "Trigeminal Neuralgia",
    "Migraine",
    "Peripheral Neuropathy",
    "Degenerative Disc ",
    "Low Back Pain",
    "Scoliosis",
    "Osteoporosis",
    "Ankylosing Spondylitis",
    "Chronic Pain",
    "Insomnia",
    "Hypertension",
    "Type 1 Diabetes",
    "Latent Autoimmune Diabetes in Adults (LADA)",
    "Morgellons ",
    "Perimenopause",
    "Hidradenitis Suppurativa",
    "Uveitis",
    "Meibomian Gland Dysfunction (MGD)",
    "Birdshot Chorioretinopathy",
    "Age-Related Macular Degeneration (AMD)",
    "Raynaud's ",
    "Pulsatile Tinnitus",
    "Dumping ",
    "Lymphocytic Colitis",
    "Congenital Sucrase-Isomaltase Deficiency (CSID)",
    "Microscopic Colitis",
    "Exocrine Pancreatic Insufficiency (EPI)",
    "Persistent Depressive Disorder",
    "Anhedonia",
    "Auditory Processing Disorder",
    "Dissociative Identity Disorder",
    "Degenerative Diskin-Neck",
    "Cervical Stenosis",
    "Spondylosis",
    "Scheuermann's ",
    "Osteopenia",
    "Chronic Pain ",
    "Thyroid Eye ",
    "Meibomian Gland Dysfunction",
    "Lichen Planus",
    "Yeast Infection",
    "Cauda Equina ",
    "Postpartum Depression",
    "Premenstr",
    "Femoroacetabular Impingement (FAI)",
    "Epicondylitis (Tennis Elbow)",
    "Ledderhose ",
    "Kienbock's ",
    "Trigger Finger",
    "Cluster Headache",
    "Tension Headache",
    "Multiple System Atrophy (MSA)",
    "Aseptic Meningitis",
    "Morton's Neuroma",
    "Achilles Tendonitis",
    "Compartment ",
    "Superior Canal Dehiscence  (SCDS)",
    "Sensorineural Hearing Loss",
    "Cholesteatoma",
    "Eustachian Tube Dysfunction",
    "Ménière's ",
    "Legg-Calve-Perthes ",
    "Femoroacetabular Impingement (FAI)",
    "Plantar Fasciitis",
    "Eosinophilic Esophagitis",
    "Barrett's Esophagus",
    "Esophageal Stricture",
    "Gastroesophageal Reflux  (GERD)",
    "Gastric Ulcers",
    "Peptic Ulcer ",
    "Celiac ",
    "Crohn's ",
    "Ulcerative Colitis",
    "Diverticulosis and Diverticulitis",
    "Irritable Bowel  (IBS)",
    "Colorectal Cancer",
    "Hemorrhoids",
    "Anal Fissure",
    "Pancreatitis",
    "Gallstones",
    "Cirrhosis",
    "Hepatitis B and C",
    "Non-Alcoholic Fatty Liver  (NAFLD)",
    "Liver Cancer",
    "Acute Kidney Injury (AKI)",
    "Chronic Kidney  (CKD)",
    "Kidney Stones",
    "Urinary Tract Infection (UTI)",
    "Interstitial Cystitis (Bladder Pain )",
    "Overactive Bladder",
    "Prostatitis",
    "Benign Prostatic Hyperplasia (BPH)",
    "Prostate Cancer",
    "Testicular Cancer",
    "Erectile Dysfunction",
    "Premature Ejaculation",
    "Hypospadias",
    "Ovarian Cysts",
    "Polycystic Ovary  (PCOS)",
    "Endometriosis",
    "Uterine Fibroids",
    "Pelvic Inflammatory  (PID)",
    "Ectopic Pregnancy",
    "Menopause Disorders",
    "Breast Cancer",
    "Cervical Cancer",
    "Ovarian Cancer",
    "Osteoarthritis",
    "Rheumatoid Arthritis",
    "Gout",
    "Fibromyalgia",
    "Osteoporosis",
    "Lupus",
    "Multiple Sclerosis",
    "Parkinson's ",
    "Huntington's ",
    "Alzheimer's ",
    "Dementia Non-Alzheimer's",
    "Stroke",
    "Epilepsy",
    "Migraine",
    "Cluster Headaches",
    "Fibromyalgia",
    "Chronic Fatigue ",
    "Lyme ",
    "Shingles (Herpes Zoster)",
    "Hepatitis A",
    "Hepatitis B",
    "Hepatitis C",
    "Cirrhosis",
    "Fatty Liver ",
    "Pancreatitis",
    "Celiac ",
    "Crohn's ",
    "Ulcerative Colitis",
    "Irritable Bowel ",
    "Diverticulitis",
    "Hemorrhoids",
    "Gallstones",
    "Kidney Stones",
    "Polycystic Kidney ",
    "Glomerulonephritis",
    "Urinary Tract Infection",
    "Bladder Infection",
    "Interstitial Cystitis",
    "Overactive Bladder",
    "Incontinence",
    "Prostatitis",
    "Benign Prostatic Hyperplasia (BPH)",
    "Erectile Dysfunction",
    "Premature Ejaculation",
    "Infertility",
    "Endometriosis",
    "Polycystic Ovary  (PCOS)",
    "Menopause Symptoms",
    "Premenstrual  (PMS)",
    "Ovarian Cysts",
    "Uterine Fibroids",
    "Pelvic Inflammatory  (PID)",
    "Chlamydia",
    "Gonorrhea",
    "Syphilis",
    "Herpes Simplex Virus (HSV)",
    "Human Papillomavirus (HPV)",
    "HIV/AIDS",
    "Hepatitis B",
    "Hepatitis C",
    "Cirrhosis",
    "Nonalcoholic Fatty Liver ",
    "Liver Cancer",
    "Pancreatitis",
    "Pancreatic Cancer",
    "Celiac ",
    "Food Allergy",
    "Lactose Intolerance",
    "Irritable Bowel  (IBS)",
    "Crohn's ",
    "Ulcerative Colitis",
    "Diverticulitis",
    "Hemorrhoids",
    "Anal Fissure",
    "Gastric Ulcer",
    "Gastric Cancer",
    "Esophageal Cancer",
    "Gastroesophageal Reflux  (GERD)",
    "Achalasia",
    "Esophagitis",
    "Barrett's Esophagus",
    "Gallstones",
    "Cholecystitis",
    "Gallbladder Cancer",
    "Kidney Stones",
    "Kidney Infection (Pyelonephritis)",
    "Kidney ",
    "Kidney Failure",
    "Renal Cell Carcinoma",
    "Bladder Infection (Cystitis)",
    "Overactive Bladder",
    "Bladder Cancer",
    "Urinary Incontinence",
    "Interstitial Cystitis",
    "Benign Prostatic Hyperplasia (BPH)",
    "Prostatitis",
    "Prostate Cancer",
    "Erectile Dysfunction",
    "Premature Ejaculation",
    "Testicular Cancer",
    "Varicocele",
    "Peyronie's ",
    "Gout",
    "Osteoarthritis" "Rheumatoid Arthritis",
    "Psoriatic Arthritis",
]
import requests
import json


def get_public_conditions(conditions):
    base_url = "https://www.stuffthatworks.health/api/search?query="
    public_conditions = []

    for condition in conditions:
        url = f"{base_url}{condition}"
        response = requests.get(url)

        # Ensure the request was successful
        if response.status_code == 200:
            data = json.loads(response.text)
            matches = data.get("matches", [])

            for match in matches:
                if match.get("conditionState") == "public":
                    public_conditions.append(match.get("entityDisplayName"))
                    print(match.get("entityDisplayName"))

    return public_conditions


def save_to_file(public_conditions, filename):
    with open(filename, "w") as f:
        json.dump(public_conditions, f)


import requests
import pandas as pd
import json


def get_public_conditions(conditions):
    base_url = "https://www.stuffthatworks.health/api/search?query="
    public_conditions = []

    total_conditions = len(conditions)

    for index, condition in enumerate(conditions):
        url = f"{base_url}{condition}"
        response = requests.get(url)

        # Ensure the request was successful
        if response.status_code == 200:
            data = json.loads(response.text)
            matches = data.get("matches", [])

            for match in matches:
                if match.get("conditionState") == "public":
                    public_conditions.append(match)

        # Calculate the percentage done and print it
        percent_done = ((index + 1) / total_conditions) * 100
        print(
            f"Processing condition {index + 1} of {total_conditions}, {percent_done}% done."
        )

    return pd.DataFrame(public_conditions)


df = get_public_conditions(listy)
df.to_csv("full_frame.csv")
