[theme]
primaryColor="#FF4B4B"
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"
secondaryTextColor="#FFBA08"
font="sans serif"

[custom_css]
url = "https://fonts.googleapis.com/css2?family=Poppins&display=swap"
